name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: true

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node }} OS: ${{ matrix.os }} Vue: ${{matrix.vue}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          run_install: true

      - name: Test
        run: pnpm test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v2

  lint:
    runs-on: ubuntu-latest
    name: "Lint source code"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint
